# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_fns": "Dicom Prep.ipynb",
         "cut_outliers": "Dicom Prep.ipynb",
         "cut_m": "Dicom Prep.ipynb",
         "cut_frame": "Dicom Prep.ipynb",
         "fix_monochrome": "Dicom Prep.ipynb",
         "normalize": "Dicom Prep.ipynb",
         "my_freqhist_bins": "Dicom Prep.ipynb",
         "my_hist_scaled": "Dicom Prep.ipynb",
         "process_dcm": "Dicom Prep.ipynb",
         "show_hist": "Dicom Prep.ipynb",
         "compare_hists": "Dicom Prep.ipynb",
         "compare_raws": "Dicom Prep.ipynb",
         "show_raw": "Dicom Prep.ipynb"}

modules = ["dicom_utils.py"]

doc_url = "https://ben-karr.github.io/dicom_utils/"

git_url = "https://github.com/ben-karr/dicom_utils/tree/master/"

def custom_doc_links(name): return None
